In [138]:
# Importing libraries
import pandas as pd

# Importing test train libraries 
from sklearn.model_selection import train_test_split

# Importing Random Forest Libraries
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Importing Warnings
import warnings
warnings.filterwarnings('ignore')

In [139]:
# Uploading files 
cars=pd.read_excel("C:\\Users\\91813\\OneDrive\\Desktop\\carData.xlsx")
cars.head(20)

car_refnum           make            trim           model cylinder  \
0           39            BMW            318i        3-Series        4   
1         1902            BMW            M40i              X3        6   
2          126  Mercedes-Benz   Gl 500 4matic        GL-Class        8   
3          596  Mercedes-Benz  Gls 500 4matic       GLS-Class        8   
4          589  Mercedes-Benz   Gl 500 4matic        GL-Class        8   
5          634       Infiniti           Other             Q30        4   
6          422    Lamborghini           Other       Aventador       12   
7          453           Audi          S-Line              Q5        4   
8          593         Nissan              Sv      Pathfinder        6   
9          607     Mitsubishi           Other          Pajero        6   
10         642  Mercedes-Benz           A 250         A-Class        4   
11         462         Nissan     Se Platinum          Patrol        6   
12         653         Nissan              Sv          Maxima        6   
13         656            BMW            M40i              X4        6   
14         615           Jeep       Unlimited        Wrangler        6   
15         624         Toyota             Gxr    Land Cruiser        8   
16         644           Jeep         Limited  Grand Cherokee        6   
17         658         Nissan              Sl           Tiida        4   
18         627         Nissan              Sl          Murano        6   
19          41           Audi           Other          S3/RS3        4   

    engine_capacity  year  mileage live_listing_date selling_date  Age  \
0               1.0  2017    70914        2021-04-19   2022-01-13  269   
1               3.0  2019    31591        2021-07-04   2022-02-03  214   
2               5.0  2016   113250        2021-09-21   2022-01-14  115   
3               5.0  2018    55421        2021-10-31   2022-01-05   66   
4               5.0  2014    99555        2021-11-01   2022-02-08   99   
5               2.0  2017    89843        2021-11-03   2022-02-11  100   
6               7.0  2014    23382        2021-11-04   2022-03-30  146   
7               2.0  2016    70139        2021-11-07   2022-01-04   58   
8               4.0  2018    36425        2021-11-07   2022-02-10   95   
9               4.0  2013   106180        2021-11-07   2022-01-12   66   
10              2.0  2016   123228        2021-11-07   2022-01-19   73   
11              4.0  2020    20873        2021-11-09   2022-01-07   59   
12              4.0  2014   152446        2021-11-10   2022-04-24  165   
13              3.0  2021    11673        2021-11-10   2022-01-27   78   
14              4.0  2017    91594        2021-11-11   2022-01-16   66   
15              5.0  2017    39760        2021-11-14   2022-01-05   52   
16              4.0  2017    95146        2021-11-15   2022-01-19   65   
17              2.0  2015    39423        2021-11-15   2022-02-07   84   
18              4.0  2014   120787        2021-11-17   2022-01-10   54   
19              2.0  2016    73598        2021-11-17   2022-01-24   68   

          vat_applicable  purchase_price  selling_price  profit_margin  
0    Full VAT Applicable         52500.0        58800.0      3015.0000  
1    Full VAT Applicable        150000.0       140000.0    -17251.7000  
2    Full VAT Applicable        110500.0       113000.0     -4265.9500  
3   Profit Margin Scheme        190000.0       195000.0      4176.9050  
4    Full VAT Applicable         78000.0        84000.0       150.0000  
5    Full VAT Applicable         70000.0        75200.0       104.0476  
6    Full VAT Applicable        750000.0       780000.0    -18807.9000  
7    Full VAT Applicable         68000.0        82000.0      8480.2380  
8   Profit Margin Scheme         80000.0        90000.0      8938.8100  
9    Full VAT Applicable         28300.0        33000.0      2543.5710  
10   Full VAT Applicable         60000.0        68000.0      3766.9050  
11  Profit Margin 

In [140]:
cars.shape

(1699, 15)

In [141]:
cars.columns

Index(['car_refnum', 'make', 'trim', 'model', 'cylinder', 'engine_capacity',
       'year', 'mileage', 'live_listing_date', 'selling_date', 'Age',
       'vat_applicable', 'purchase_price', 'selling_price', 'profit_margin'],
      dtype='object')

In [142]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1699 entries, 0 to 1698
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   car_refnum         1699 non-null   int64         
 1   make               1699 non-null   object        
 2   trim               1695 non-null   object        
 3   model              1699 non-null   object        
 4   cylinder           1699 non-null   object        
 5   engine_capacity    1697 non-null   float64       
 6   year               1699 non-null   int64         
 7   mileage            1699 non-null   int64         
 8   live_listing_date  1699 non-null   datetime64[ns]
 9   selling_date       1699 non-null   datetime64[ns]
 10  Age                1699 non-null   int64         
 11  vat_applicable     1699 non-null   object        
 12  purchase_price     1699 non-null   float64       
 13  selling_price      1699 non-null   float64       
 14  profit_m

In [143]:
cars.dtypes

car_refnum                    int64
make                         object
trim                         object
model                        object
cylinder                     object
engine_capacity             float64
year                          int64
mileage                       int64
live_listing_date    datetime64[ns]
selling_date         datetime64[ns]
Age                           int64
vat_applicable               object
purchase_price              float64
selling_price               float64
profit_margin               float64
dtype: object

In [144]:
cars.describe()

car_refnum  engine_capacity         year       mileage          Age  \
count   1699.000000      1697.000000  1699.000000    1699.00000  1699.000000   
mean   20231.787522       646.474956  2017.736315   65708.77163    49.476162   
std    15197.051030      1247.917587     2.495682   36519.71031    45.798940   
min       13.000000         1.000000  2008.000000       9.00000     0.000000   
25%     7663.500000         2.000000  2016.000000   36554.50000    15.000000   
50%    15388.000000         3.000000  2018.000000   66812.00000    36.000000   
75%    32082.000000        75.000000  2020.000000   93666.50000    70.000000   
max    55043.000000      6400.000000  2023.000000  187900.00000   302.000000   

       purchase_price  selling_price  profit_margin  
count     1699.000000    1699.000000    1699.000000  
mean     88388.631842   99347.902001    7818.569292  
std      65895.002463   70159.901324    9519.635269  
min      10300.000000   17000.000000  -77602.900000  
25%      43000.000000   50000.000000    2738.643000  
50%      67500.000000   77000.000000    6589.048000  
75%     115000.000000  127000.000000   11701.310000  
max     750000.000000  780000.000000  103269.500000

In [145]:
# checking null values
cars.isnull().sum()

car_refnum           0
make                 0
trim                 4
model                0
cylinder             0
engine_capacity      2
year                 0
mileage              0
live_listing_date    0
selling_date         0
Age                  0
vat_applicable       0
purchase_price       0
selling_price        0
profit_margin        0
dtype: int64

In [146]:
# Removing the null values
cars = cars.dropna()

In [147]:
# Checking for dulicate values
cars[cars.duplicated()]

Empty DataFrame
Columns: [car_refnum, make, trim, model, cylinder, engine_capacity, year, mileage, live_listing_date, selling_date, Age, vat_applicable, purchase_price, selling_price, profit_margin]
Index: []

#### No dulplicate values present

In [148]:
# Droping unwanted columns
cars1=cars.drop(['car_refnum','vat_applicable','live_listing_date','selling_date','Age'],axis=1)
cars1.head()
df=cars1

In [149]:
df.dtypes

make                object
trim                object
model               object
cylinder            object
engine_capacity    float64
year                 int64
mileage              int64
purchase_price     float64
selling_price      float64
profit_margin      float64
dtype: object

In [150]:
# Split the data into features (X) and target variable (y)
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

# Performing one-hot encoding for categorical variables
X = pd.get_dummies(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [151]:
# Initialize the model
car_model = RandomForestRegressor(random_state=42)
print("xtrain",X_train)
print("ytrain",y_train)

# Train the model
car_model.fit(X_train, y_train)

xtrain       engine_capacity  year  mileage  purchase_price  profit_margin  \
1391              2.0  2019    44482         66000.0     13534.1000   
756               2.0  2016   103490         50000.0      -738.5240   
411               4.0  2013   103420         23500.0      3533.0950   
1659           2000.0  2016    77132         59500.0     13295.7100   
1222           2000.0  2018    57466         68000.0      5888.4290   
...               ...   ...      ...             ...            ...   
1136              1.0  2019    92856         24950.0       958.5714   
1300           2000.0  2019    57430        148000.0      -998.5710   
866            2500.0  2019    95469         59000.0      7125.7140   
1465              5.0  2020    74157         99000.0       492.3810   
1132           1500.0  2020    70196         26850.0      5821.9050   

      make_Alfa Romeo  make_Audi  make_BMW  make_Bentley  make_Bestune  ...  \
1391                0          0         0             0     

RandomForestRegressor(random_state=42)

In [152]:
# Assuming X_train is your training data
X_test_array = X_test[X_train.columns].values


In [153]:
# Predicting the model
predictions = car_model.predict(X_test_array)

In [154]:
joblib.dump(car_model, 'car_model.joblib')


['car_model.joblib']

In [155]:
print(type(X_test_array))
print(X_test_array)

<class 'numpy.ndarray'>
[[1.0000e+00 2.0170e+03 6.5077e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [2.0000e+00 2.0160e+03 7.5303e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [3.0000e+00 2.0180e+03 6.3507e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [3.0000e+03 2.0160e+03 8.9281e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [3.0000e+03 2.0180e+03 6.6210e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [4.0000e+00 2.0190e+03 6.6251e+04 ... 0.0000e+00 0.0000e+00 0.0000e+00]]


In [156]:
print("predictions", predictions)

predictions [ 27609.     74084.98  174680.     35723.98  190634.99   34008.91
  33314.96  121929.97  160526.     97510.     54086.81   86243.99
  24756.88   68959.98   39220.     30077.     26049.93  339020.
  76191.97  110297.     68201.53   57878.    199240.    145060.
  88504.96   68409.84   89385.    189295.     93309.95  211969.84
 186179.99  117949.87  247558.    127019.95   45380.     52256.
  70722.99  227620.     55140.98   75919.97   42000.     35939.03
 181139.96   66580.     87570.    170040.     50563.98   25916.5
 116004.9   189890.     54343.8   144500.     60079.98   58182.
  51752.     38478.92   86419.94   59297.98   39749.    135130.
 157309.96   38596.     63340.    126859.99   73377.98   64189.66
  50305.    155097.    223311.     57447.     56192.84   43880.
  98400.    175680.    184759.98  218880.     96480.     21204.86
 208495.     28313.98  283790.    153270.     59207.51  118998.4
 141938.97   83177.94   59676.     54796.34   41077.99  113020.89
  44995.    

In [157]:
# Finding MAE
mae = mean_absolute_error(y_test, predictions)
print(f'Mean Absolute Error: {mae}')

Mean Absolute Error: 2502.465368731563


In [158]:
# Finding R2 Values
from sklearn.metrics import r2_score

r2 = r2_score(y_test, predictions)

print(f'R-squared: {r2}')


R-squared: 0.9927681084027231


In [159]:
# Creating a DataFrame with actual and predicted values
results_df = pd.DataFrame({'Actual': y_test, 'Predicted': predictions.flatten()})
results_df.to_csv('model_predictions.csv', index=False)
print(results_df)

        Actual  Predicted
1269   28000.0   27609.00
1691   78000.0   74084.98
1562  175000.0  174680.00
1182   35000.0   35723.98
1380  193000.0  190634.99
...        ...        ...
547    70000.0   69245.00
1117   99000.0  103039.00
993   138000.0  139239.72
1181   75000.0   72969.98
1489   75000.0   75954.00

[339 rows x 2 columns]


### EX 1

In [160]:
import joblib
loaded_model = joblib.load('C:\\Users\\91813\\OneDrive\\Desktop\\car_model.joblib')

In [171]:
# Collecting user input 
user_input = {
    'make': 'BMW',
    'trim': '318i',
    'model': '3-Series',
    'cylinder': 6,
    'engine_capacity': 2.0,
    'year': 2020,
    'mileage': 65000,
    'purchase_price': 25555,
    'profit_margin': 2000
}

# Creating DataFrame
user_input_df = pd.DataFrame([user_input])

# Get the one-hot encoded columns from the training data
one_hot_cols_train = pd.get_dummies(X_train).columns

# Preprocess the user input (include only the relevant columns for one-hot encoding)
user_input_df_encoded = pd.get_dummies(user_input_df)
user_input_df_encoded = user_input_df_encoded.reindex(columns=one_hot_cols_train, fill_value=0)

# Make predictions
user_predictions = loaded_model.predict(user_input_df_encoded)

# Displaying the predicted output
print('Predicted Price:', user_predictions[0])


Predicted Price: 28714.1


## EX 2

In [168]:
user_input1 = {
    'make': 'Mercedes-Benz',
    'trim': 'Gls 500 4matic',
    'model': 'GLS-Class',
    'cylinder': 4,
    'engine_capacity': 5.0,
    'year': 2015,
    'mileage': 70000,
    'purchase_price': 85555,
    'profit_margin': 6000
}

In [170]:
# Creating DataFrame
user_input_df1 = pd.DataFrame([user_input1])

# Get the one-hot encoded columns from the training data
one_hot_cols_train1 = pd.get_dummies(X_train).columns

# Preprocess the user input (include only the relevant columns for one-hot encoding)
user_input_df_encoded1 = pd.get_dummies(user_input_df1)
user_input_df_encoded1 = user_input_df_encoded1.reindex(columns=one_hot_cols_train, fill_value=0)

# Make predictions
user_predictions1 = loaded_model.predict(user_input_df_encoded1)

# Displaying the predicted output
print('Predicted Price:', user_predictions1[0])

Predicted Price: 96710.0
